export const CANDIDATE_SET_LIST = "CANDIDATES_SET_LIST";

export const CANDIDATE_UPDATE_STEP = "CANDIDATE_UPDATE_STEP";

export const FILTER_SET_TEXT = "FILTER_SET_TEXT";
export const FILTER_SET_STEP = "FILTER_SET_STEP";
